-- AlterTable
ALTER TABLE "User" ADD COLUMN     "blocked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "loanBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "savingsBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
